import { join } from 'node:path';

const reanimated = require('react-native-reanimated') as Record<string, unknown>;
const transition = {
  damping: jest.fn(() => transition),
  reduceMotion: jest.fn(() => transition),
};
reanimated.runOnUI = (worklet: (...args: unknown[]) => unknown) => worklet;
reanimated.SharedTransition = { springify: () => transition };
(reanimated.default as Record<string, unknown>).addWhitelistedNativeProps = jest.fn();

const modules = [
  'src/app/(tabs)/_layout.tsx',
  'src/app/(tabs)/profile/account.tsx',
  'src/app/(tabs)/profile/api-usage.tsx',
  'src/app/(tabs)/profile/design-system.tsx',
  'src/app/(tabs)/profile/developer.tsx',
  'src/app/(tabs)/profile/index.tsx',
  'src/app/(tabs)/profile/integrations.tsx',
  'src/app/_layout.tsx',
  'src/app/account.tsx',
  'src/app/activity-form-assistant.tsx',
  'src/app/activity-form-copy.ts',
  'src/app/activity-form-detail-editors.tsx',
  'src/app/activity-form-editors.tsx',
  'src/app/activity-form-missing.tsx',
  'src/app/activity-form-styles.ts',
  'src/app/auth/data-choice.tsx',
  'src/app/welcome.tsx',
  'src/components/navigation/navigation-session-sync.tsx',
  'src/components/primitives/date-field.web.tsx',
  'src/components/primitives/time-field.web.tsx',
  'src/features/account/api-usage-screen.tsx',
  'src/features/account/avatar-color-picker.tsx',
  'src/features/account/city-autofind-settings-row.tsx',
  'src/features/account/city-autofind-suggestion-menu.tsx',
  'src/features/account/cloud-account-card.tsx',
  'src/features/account/developer-hub.tsx',
  'src/features/account/developer-insights-panel.tsx',
  'src/features/account/developer-release-notes-panel.tsx',
  'src/features/account/developer-storage.ts',
  'src/features/account/iconify-search.ts',
  'src/features/account/integrations-service-card.tsx',
  'src/features/account/integrations-status-card.tsx',
  'src/features/account/profile-avatar-editor-sheet.tsx',
  'src/features/account/profile-identity-editor-sheet.tsx',
  'src/features/account/profile-location-preferences.tsx',
  'src/features/account/use-city-autofind-suggestions.ts',
  'src/features/analytics/usage-analytics-tracker.tsx',
  'src/features/calendar/month-grid.tsx',
  'src/features/daily-tracking/use-place-weather.ts',
  'src/features/design-system/design-system-theme-history.tsx',
  'src/features/design-system/design-system-colors-panel.tsx',
  'src/features/design-system/design-system-components-panel.tsx',
  'src/features/design-system/design-system-fonts-panel.tsx',
  'src/features/design-system/design-system-forms-panel.tsx',
  'src/features/finance/credit-providers.ts',
  'src/features/finance/finance-credit-sheet.tsx',
  'src/features/finance/finance-progress-bar.tsx',
  'src/features/finance/finance-tax-handoff-sheet.tsx',
  'src/features/finance/persist-finance-document.ts',
  'src/features/finance/share-tax-package.ts',
  'src/features/finance/use-finance-coach.ts',
  'src/features/food/grocery-item-editor-sheet.tsx',
  'src/features/food/scan-ingredient-review.tsx',
  'src/features/games/balloon-pop/balloon-pop-hud.tsx',
  'src/features/games/balloon-pop/balloon-pop-stage.tsx',
  'src/features/games/balloon-pop/colors.ts',
  'src/features/social/social-feed.tsx',
  'src/features/social/social-hub-sections.tsx',
  'src/features/social/social-upcoming-together.tsx',
  'src/features/todos/grocery-list-header.tsx',
  'src/features/todos/grocery-list-screen-styles.ts',
  'src/features/todos/recipe-import-draft-panel.tsx',
  'src/features/todos/recipe-import-helpers.ts',
  'src/features/todos/recipe-import-screen-styles.ts',
  'src/features/todos/recipe-ingredient-editor.tsx',
  'src/features/todos/todo-list-settings-sharing.tsx',
  'src/features/todos/todo-list-settings-styles.ts',
  'src/features/todos/use-voice-lists-sync.ts',
  'src/features/travel/confirmation-document-cue.tsx',
  'src/features/travel/confirmation-import-banner.tsx',
  'src/features/travel/expenses/currency-dropdown.tsx',
  'src/features/travel/flight-details-card-editor.tsx',
  'src/features/travel/flight-details-editor.tsx',
  'src/features/travel/flight-details-summary.tsx',
  'src/features/travel/flight-return-leg-fields.tsx',
  'src/features/travel/rental-details-card-editor.tsx',
  'src/features/travel/rental-details-editor.tsx',
  'src/features/travel/rental-details-summary.tsx',
  'src/features/travel/stay-details-card-editor.tsx',
  'src/features/travel/stay-details-editor.tsx',
  'src/features/travel/stay-details-summary.tsx',
  'src/features/travel/stay-expense-from-import.ts',
  'src/features/travel/transport-attachments.ts',
  'src/features/travel/transport-details-card-editor.tsx',
  'src/features/travel/transport-details-editor.tsx',
  'src/features/travel/transport-details-summary.tsx',
  'src/features/travel/travel-cotraveler-stack.tsx',
  'src/features/travel/travel-currency-chrome.ts',
  'src/features/travel/travel-currency-rate-panel.tsx',
  'src/features/travel/travel-currency-sheet-body.tsx',
  'src/features/travel/travel-currency-sheet.styles.ts',
  'src/features/travel/travel-currency-side-card.tsx',
  'src/features/travel/travel-friends-join-panels.tsx',
  'src/features/travel/travel-friends-roster-model.ts',
  'src/features/travel/travel-itinerary-form-schedule-fields.tsx',
  'src/features/travel/travel-itinerary-stay-fields.tsx',
  'src/features/travel/travel-join-link-display.ts',
  'src/features/travel/travel-mode-picker.tsx',
  'src/features/travel/travel-photo-lightbox.tsx',
  'src/features/travel/travel-plan-actions.tsx',
  'src/features/travel/travel-range-fields.tsx',
  'src/features/travel/upgrade-legacy-connecting-flights.ts',
  'src/features/travel/use-auto-growing-note.ts',
  'src/features/travel/use-travel-currency-sheet-state.ts',
  'src/features/travel/use-travel-friends-sheet-actions.ts',
  'src/features/travel/use-travel-friends-sheet-sync.ts',
  'src/features/vision-board/vision-board-background.tsx',
  'src/features/workouts/muscle-highlight-plate.tsx',
  'src/features/workouts/bench-press-animation.tsx',
  'src/features/workouts/exercise-anatomy-still.tsx',
  'src/features/workouts/front-plank-animation.tsx',
  'src/features/workouts/generic-anatomy-figure.tsx',
  'src/features/workouts/human-body-map.tsx',
  'src/hooks/use-apply-ota-update.ts',
  'src/hooks/use-friends-realtime.ts',
  'src/hooks/use-hydrated.ts',
  'src/hooks/use-meal-photo-migration.ts',
  'src/hooks/use-root-startup-effects.ts',
  'src/hooks/use-todo-collaboration.ts',
  'src/hooks/use-vehicle-collaboration.ts',
  'src/services/analytics/sync.ts',
  'src/services/health/action-suggestions-client.ts',
  'src/services/health/apple-health.ts',
  'src/services/http/api-usage-client.ts',
  'src/services/movies/index.ts',
  'src/utils/scroll-anchor-into-view.ts',
  'src/utils/defer-until-idle.ts',
] as const;

describe('remaining runtime module smoke coverage', () => {
  it.each(modules)('%s loads and exposes a runtime API', (relative) => {
    const loaded = require(join(process.cwd(), relative)) as Record<string, unknown>;
    expect(Object.keys(loaded).length).toBeGreaterThan(0);
  });
});
