/** Shell / non-travel / non-food agent-ui testIDs (composed into AgentUiIds). */

import { agentUiIdsShellDaily } from './ids-shell-daily';
import { agentUiIdsShellProfile } from './ids-shell-profile';

export const agentUiIdsShell = {
  shell: {
    swipeBack: 'ontrack.shell.swipeBack',
    swipeForward: 'ontrack.shell.swipeForward',
  },
  sheet: {
    /** Layout anchor for the visible SheetScaffold plate (not tappable). */
    plate: 'ontrack.sheet.plate',
  },
  tabs: {
    overview: 'ontrack.tabs.overview',
    today: 'ontrack.tabs.today',
    calendar: 'ontrack.tabs.calendar',
    checklists: 'ontrack.tabs.checklists',
    social: 'ontrack.tabs.social',
    insights: 'ontrack.tabs.insights',
    profile: 'ontrack.tabs.profile',
    workouts: 'ontrack.tabs.workouts',
    plants: 'ontrack.tabs.plants',
    travel: 'ontrack.tabs.travel',
    visionBoard: 'ontrack.tabs.visionBoard',
    games: 'ontrack.tabs.games',
    vehicles: 'ontrack.tabs.vehicles',
    health: 'ontrack.tabs.health',
    finance: 'ontrack.tabs.finance',
    journal: 'ontrack.tabs.journal',
    food: 'ontrack.tabs.food',
    /** More → Trackers (pin/reorder hub). */
    more: 'ontrack.tabs.more',
    carouselPrev: 'ontrack.tabs.carousel.prev',
    carouselNext: 'ontrack.tabs.carousel.next',
    /** Layout anchor for the page-matching bottom nav fill (not tappable). */
    dock: 'ontrack.tabs.dock',
    search: 'ontrack.tabs.search',
    searchField: 'ontrack.tabs.search.field',
    searchMic: 'ontrack.tabs.search.mic',
    searchStop: 'ontrack.tabs.search.stop',
    searchSend: 'ontrack.tabs.search.send',
    searchClear: 'ontrack.tabs.search.clear',
    searchClose: 'ontrack.tabs.search.close',
    searchBackdrop: 'ontrack.tabs.search.backdrop',
    /** Layout anchor for the expanded search results scroller (not tappable). */
    searchResults: 'ontrack.tabs.search.results',
    searchTranscript: 'ontrack.tabs.search.transcript',
    searchClearConversation: 'ontrack.tabs.search.clearConversation',
    searchResult: (id: string) =>
      `ontrack.tabs.search.result.${id.replace(/[^a-zA-Z0-9]+/g, '_')}`,
  },
  overview: {
    screen: 'ontrack.overview.screen',
    hero: 'ontrack.overview.hero',
    eventUpdates: 'ontrack.overview.eventUpdates',
    section: 'ontrack.overview.section.all',
    acknowledge: (key: string) =>
      `ontrack.overview.attention.acknowledge.${key.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    row: (routeName: string) => `ontrack.overview.row.${routeName.replace(/[^a-zA-Z0-9]+/g, '_')}`,
  },
  trackers: {
    screen: 'ontrack.trackers.screen',
    row: (routeName: string) => `ontrack.trackers.row.${routeName.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    add: (routeName: string) => `ontrack.trackers.add.${routeName.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    remove: (routeName: string) =>
      `ontrack.trackers.remove.${routeName.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    drag: (routeName: string) =>
      `ontrack.trackers.drag.${routeName.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    pinCount: (extras: 3 | 5) => `ontrack.trackers.pinCount.${extras}`,
    pinCountSection: 'ontrack.trackers.section.pinCount',
    manage: 'ontrack.trackers.manage',
    manageSheet: 'ontrack.trackers.manage.sheet',
    manageClose: 'ontrack.trackers.manage.close',
    addon: (addonId: string) =>
      `ontrack.trackers.addon.${addonId.replace(/[^a-zA-Z0-9]+/g, '_')}`,
  },
  health: {
    settings: 'ontrack.health.settings',
    privacy: 'ontrack.health.privacy',
    section: (section: string) => `ontrack.health.section.${section}`,
    connect: 'ontrack.health.body.connect',
    refresh: 'ontrack.health.body.refresh',
    openAppleHealth: 'ontrack.health.body.openAppleHealth',
    sleepHandoff: 'ontrack.health.body.sleepHandoff',
    range: (days: number) => `ontrack.health.body.range.${days}`,
    checkIn: 'ontrack.health.mind.checkIn',
    addFactor: 'ontrack.health.mind.addFactor',
    moodEntry: (id: string) => `ontrack.health.mind.entry.${id}`,
    editFactor: (id: string) => `ontrack.health.mind.factor.${id}.edit`,
    addPlaybook: 'ontrack.health.mind.addPlaybook',
    editPlaybook: (id: string) => `ontrack.health.playbook.${id}.edit`,
    startPlaybook: (id: string) => `ontrack.health.playbook.${id}.start`,
    completePlaybook: (id: string) => `ontrack.health.playbookRun.${id}.complete`,
    cancelPlaybook: (id: string) => `ontrack.health.playbookRun.${id}.cancel`,
    call988: 'ontrack.health.support.call988',
    text988: 'ontrack.health.support.text988',
    emotion: (id: string) => `ontrack.health.checkIn.emotion.${id}`,
    intensity: (id: string, value: number) => `ontrack.health.checkIn.intensity.${id}.${value}`,
    factor: (id: string) => `ontrack.health.checkIn.factor.${id}`,
    note: 'ontrack.health.checkIn.note',
    customEmotion: 'ontrack.health.checkIn.customEmotion',
    addCustomEmotion: 'ontrack.health.checkIn.addCustomEmotion',
    stateKind: (kind: string) => `ontrack.health.checkIn.stateKind.${kind}`,
    valence: (value: string) => `ontrack.health.checkIn.valence.${value}`,
    saveCheckIn: 'ontrack.health.checkIn.save',
    factorName: 'ontrack.health.factor.name',
    factorCategory: (category: string) => `ontrack.health.factor.category.${category}`,
    factorEmotion: (id: string) => `ontrack.health.factor.emotion.${id}`,
    saveFactor: 'ontrack.health.factor.save',
    deleteFactor: 'ontrack.health.factor.delete',
    playbookName: 'ontrack.health.playbook.name',
    playbookEmotion: (group: string, id: string) => `ontrack.health.playbook.${group}.${id}`,
    playbookSteps: 'ontrack.health.playbook.steps',
    playbookDuration: 'ontrack.health.playbook.duration',
    savePlaybook: 'ontrack.health.playbook.save',
    deletePlaybook: 'ontrack.health.playbook.delete',
    suggestPlaybook: 'ontrack.health.playbook.suggest',
    useSuggestion: (index: number) => `ontrack.health.playbook.suggestion.${index}.use`,
    settingsConnect: 'ontrack.health.settings.connect',
    openAppleHealthSettings: 'ontrack.health.settings.openAppleHealth',
    stateSync: (value: string) => `ontrack.health.settings.stateSync.${value}`,
    reset: 'ontrack.health.settings.reset',
  },
  vehicles: {
    add: 'ontrack.vehicles.list.add',
    vehicle: (vehicleId: string) => `ontrack.vehicles.list.vehicle.${vehicleId}`,
    settings: 'ontrack.vehicles.detail.settings',
    section: (section: string) => `ontrack.vehicles.detail.section.${section}`,
    saveOdometer: 'ontrack.vehicles.detail.saveOdometer',
    overviewSettingsTip: (vehicleId: string) =>
      `ontrack.vehicles.detail.overviewSettingsTip.${vehicleId}`,
    new: {
      nickname: 'ontrack.vehicles.new.nickname',
      year: 'ontrack.vehicles.new.year',
      make: 'ontrack.vehicles.new.make',
      model: 'ontrack.vehicles.new.model',
      vin: 'ontrack.vehicles.new.vin',
      odometer: 'ontrack.vehicles.new.odometer',
      save: 'ontrack.vehicles.new.save',
      cancel: 'ontrack.vehicles.new.cancel',
    },
    expenses: {
      title: 'ontrack.vehicles.expenses.title',
      amount: 'ontrack.vehicles.expenses.amount',
      date: 'ontrack.vehicles.expenses.date',
      category: (category: string) => `ontrack.vehicles.expenses.category.${category}`,
      notes: 'ontrack.vehicles.expenses.notes',
      add: 'ontrack.vehicles.expenses.add',
      delete: (expenseId: string) => `ontrack.vehicles.expenses.delete.${expenseId}`,
      confirmDelete: 'ontrack.vehicles.expenses.confirmDelete',
    },
  },
  ...agentUiIdsShellDaily,
  checklists: {
    editMode: 'ontrack.checklists.editMode',
    collaborators: 'ontrack.checklists.collaborators',
    newListName: 'ontrack.checklists.newListName',
    createList: 'ontrack.checklists.createList',
    newListKind: (kind: string) => `ontrack.checklists.newListKind.${kind}`,
    list: (listId: string) => `ontrack.checklists.list.${listId}`,
    listName: (listId: string) => `ontrack.checklists.listName.${listId}`,
    detail: {
      back: 'ontrack.checklists.detail.back',
      title: 'ontrack.checklists.detail.title',
      filter: 'ontrack.checklists.detail.filter',
      newTask: 'ontrack.checklists.detail.newTask',
      addTask: 'ontrack.checklists.detail.addTask',
      sort: 'ontrack.checklists.detail.sort',
      sortOption: (id: string) => `ontrack.checklists.detail.sort.${id}`,
      assigneeFilter: 'ontrack.checklists.detail.assigneeFilter',
      assigneeOption: (assigneeId: string) =>
        `ontrack.checklists.detail.assigneeOption.${assigneeId}`,
      actions: 'ontrack.checklists.detail.actions',
      actionsClose: 'ontrack.checklists.detail.actionsClose',
      action: (action: string) => `ontrack.checklists.detail.action.${action}`,
      categoryTabs: 'ontrack.checklists.detail.categoryTabs',
      category: (categoryId: string) => `ontrack.checklists.detail.category.${categoryId}`,
      editMode: 'ontrack.checklists.detail.editMode',
      linkedTrip: 'ontrack.checklists.detail.linkedTrip',
      task: (taskId: string) => `ontrack.checklists.detail.task.${taskId}`,
    },
    itemDetails: {
      close: 'ontrack.checklists.itemDetails.close',
      title: 'ontrack.checklists.itemDetails.title',
      saveTitle: 'ontrack.checklists.itemDetails.saveTitle',
      assignee: 'ontrack.checklists.itemDetails.assignee',
      assigneeOption: (userId: string) => `ontrack.checklists.itemDetails.assigneeOption.${userId}`,
      category: 'ontrack.checklists.itemDetails.category',
      categoryOption: (categoryId: string) =>
        `ontrack.checklists.itemDetails.categoryOption.${categoryId}`,
      newCategoryName: 'ontrack.checklists.itemDetails.newCategoryName',
      createCategory: 'ontrack.checklists.itemDetails.createCategory',
    },
  },
  grocery: {
    back: 'ontrack.grocery.detail.back',
    addRecipe: 'ontrack.grocery.detail.addRecipe',
    settings: 'ontrack.grocery.detail.settings',
    share: 'ontrack.grocery.detail.share',
    copy: 'ontrack.grocery.detail.copy',
    view: (view: string) => `ontrack.grocery.detail.view.${view}`,
    recipe: (recipeId: string) => `ontrack.grocery.detail.recipe.${recipeId}`,
    task: (taskId: string) => `ontrack.grocery.detail.task.${taskId}`,
    combinedItem: (groupId: string) => `ontrack.grocery.detail.combined.${groupId}`,
  },
  recipeImport: {
    cancel: 'ontrack.recipeImport.cancel',
    stop: 'ontrack.recipeImport.stop',
    url: 'ontrack.recipeImport.url',
    analyze: 'ontrack.recipeImport.analyze',
    camera: 'ontrack.recipeImport.camera',
    library: 'ontrack.recipeImport.library',
    mealName: 'ontrack.recipeImport.mealName',
    sourceUrl: 'ontrack.recipeImport.sourceUrl',
    sourceServings: 'ontrack.recipeImport.sourceServings',
    targetServings: 'ontrack.recipeImport.targetServings',
    addIngredient: 'ontrack.recipeImport.ingredient.add',
    ingredientName: (ingredientId: string) =>
      `ontrack.recipeImport.ingredient.${ingredientId}.name`,
    removeIngredient: (ingredientId: string) =>
      `ontrack.recipeImport.ingredient.${ingredientId}.remove`,
    save: 'ontrack.recipeImport.save',
  },
  plants: {
    add: 'ontrack.plants.list.add',
    plant: (plantId: string) => `ontrack.plants.list.plant.${plantId}`,
    detail: {
      edit: 'ontrack.plants.detail.edit',
      amount: 'ontrack.plants.detail.amount',
      logWatering: 'ontrack.plants.detail.logWatering',
      adjustSchedule: 'ontrack.plants.detail.adjustSchedule',
      undoWatering: 'ontrack.plants.detail.undoWatering',
      checkIn: 'ontrack.plants.detail.checkIn',
      delete: 'ontrack.plants.detail.delete',
    },
    calendarSheet: {
      openDetails: 'ontrack.plants.calendarSheet.openDetails',
    },
    new: {
      camera: 'ontrack.plants.new.camera',
      library: 'ontrack.plants.new.library',
      analyze: 'ontrack.plants.new.analyze',
      confirmIdentity: 'ontrack.plants.new.confirmIdentity',
      nickname: 'ontrack.plants.new.nickname',
      buildCarePlan: 'ontrack.plants.new.buildCarePlan',
      save: 'ontrack.plants.new.save',
    },
  },
  peoplePicker: {
    close: 'ontrack.peoplePicker.close',
    dropdown: 'ontrack.peoplePicker.dropdown',
    search: 'ontrack.peoplePicker.search',
    empty: 'ontrack.peoplePicker.empty',
    friend: (friendId: string) => `ontrack.peoplePicker.friend.${friendId}`,
    confirm: 'ontrack.peoplePicker.confirm',
  },
  workouts: {
    customPlanner: 'ontrack.workouts.header.customPlanner',
    exploreMuscles: 'ontrack.workouts.exploreMuscles',
    /** Legacy Today-plan ids kept for the still-supported standalone panel. */
    planFromScratch: 'ontrack.workouts.today.planFromScratch',
    todayPlan: (activityId: string) => `ontrack.workouts.todayPlan.${activityId}`,
    selectedDaySection: 'ontrack.workouts.selectedDay.section',
    selectedDayPrevious: 'ontrack.workouts.selectedDay.previous',
    selectedDayNext: 'ontrack.workouts.selectedDay.next',
    selectedDayEditWorkout: (activityId: string) => `ontrack.workouts.selectedDay.editWorkout.${activityId}`,
    selectedDayPlan: 'ontrack.workouts.selectedDay.plan',
    dayPlanner: {
      section: 'ontrack.workouts.dayPlanner.section',
      close: 'ontrack.workouts.dayPlanner.close',
      backdrop: 'ontrack.workouts.dayPlanner.backdrop',
      title: 'ontrack.workouts.dayPlanner.title',
      startTime: 'ontrack.workouts.dayPlanner.startTime',
      durationHours: 'ontrack.workouts.dayPlanner.durationHours',
      durationMinutes: 'ontrack.workouts.dayPlanner.durationMinutes',
      type: (type: string) => `ontrack.workouts.dayPlanner.type.${type}`,
      exerciseName: (exerciseId: string) => `ontrack.workouts.dayPlanner.exercise.${exerciseId}.name`,
      exerciseRest: (exerciseId: string) => `ontrack.workouts.dayPlanner.exercise.${exerciseId}.rest`,
      addExercise: 'ontrack.workouts.dayPlanner.addExercise',
      removeExercise: (exerciseId: string) => `ontrack.workouts.dayPlanner.exercise.${exerciseId}.remove`,
      addSet: (exerciseId: string) => `ontrack.workouts.dayPlanner.exercise.${exerciseId}.addSet`,
      setReps: (setId: string) => `ontrack.workouts.dayPlanner.set.${setId}.reps`,
      setWeight: (setId: string) => `ontrack.workouts.dayPlanner.set.${setId}.weight`,
      removeSet: (setId: string) => `ontrack.workouts.dayPlanner.set.${setId}.remove`,
      save: 'ontrack.workouts.dayPlanner.save',
    },
    builderClear: 'ontrack.workouts.builder.clear',
    addToToday: 'ontrack.workouts.builder.addToToday',
    addToDay: 'ontrack.workouts.builder.addToDay',
    exerciseAdd: (exerciseId: string) => `ontrack.workouts.exercise.${exerciseId}.add`,
    exercisePreview: (exerciseId: string) => `ontrack.workouts.exercise.${exerciseId}.preview`,
    anatomySex: (sex: string) => `ontrack.workouts.explorer.anatomySex.${sex}`,
    bodyView: (view: string) => `ontrack.workouts.explorer.bodyView.${view}`,
    muscleChip: (muscleKey: string) => `ontrack.workouts.explorer.muscle.${muscleKey}`,
    gym: {
      edit: 'ontrack.workouts.gym.edit',
      start: 'ontrack.workouts.gym.start',
      close: 'ontrack.workouts.gym.close',
      completeSet: 'ontrack.workouts.gymActive.completeSet',
      finish: 'ontrack.workouts.gymActive.finish',
    },
  },
  vision: {
    dashboardFilter: 'ontrack.vision.dashboard.filter',
    dashboardAdd: 'ontrack.vision.dashboard.add',
    dashboardViewAll: 'ontrack.vision.dashboard.viewAll',
    dashboardEdit: 'ontrack.vision.dashboard.edit',
    dashboardCategory: (categoryId: string) => `ontrack.vision.dashboard.category.${categoryId}`,
    consolidatedSearch: 'ontrack.vision.consolidated.search',
    consolidatedMore: 'ontrack.vision.consolidated.more',
    consolidatedCategory: (categoryId: string) =>
      `ontrack.vision.consolidated.category.${categoryId}`,
    categoryMode: 'ontrack.vision.category.mode',
    addImage: 'ontrack.vision.category.addImage',
    addAffirmation: 'ontrack.vision.category.addAffirmation',
    addGoal: 'ontrack.vision.category.addGoal',
    canvasItem: (itemId: string) => `ontrack.vision.category.canvasItem.${itemId}`,
    selectionDeselect: 'ontrack.vision.category.selection.deselect',
    selectionEdit: 'ontrack.vision.category.selection.edit',
    selectionLayerBack: 'ontrack.vision.category.selection.layerBack',
    selectionLayerForward: 'ontrack.vision.category.selection.layerForward',
    selectionDelete: 'ontrack.vision.category.selection.delete',
    itemPrimary: 'ontrack.vision.itemEditor.primary',
    itemSecondary: 'ontrack.vision.itemEditor.secondary',
    itemSave: 'ontrack.vision.itemEditor.save',
    itemClose: 'ontrack.vision.itemEditor.close',
  },
  listSettings: {
    close: 'ontrack.listSettings.close',
    name: 'ontrack.listSettings.name',
    saveName: 'ontrack.listSettings.saveName',
    addEditors: 'ontrack.listSettings.addEditors',
    editor: (userId: string) => `ontrack.listSettings.editor.${userId}`,
    confirmEditors: 'ontrack.listSettings.confirmEditors',
    makeEditor: (userId: string) => `ontrack.listSettings.makeEditor.${userId}`,
    makeMember: (userId: string) => `ontrack.listSettings.makeMember.${userId}`,
  },
  ...agentUiIdsShellProfile,
  games: {
    challengeFriend: 'ontrack.games.hub.challengeFriend',
    balloonPopCard: 'ontrack.games.hub.balloonPop',
    balloonPopPlay: 'ontrack.games.balloonPop.play',
    balloonPopRetry: 'ontrack.games.balloonPop.retry',
    balloonPopBack: 'ontrack.games.balloonPop.back',
    balloonPopClose: 'ontrack.games.balloonPop.close',
    balloon: (balloonId: string) => `ontrack.games.balloonPop.balloon.${balloonId}`,
  },
  prompt: {
    close: 'ontrack.prompt.close',
    messageScroll: 'ontrack.prompt.messageScroll',
    action: (index: number) => `ontrack.prompt.action.${index}`,
  },
  eventDetail: {
    edit: 'ontrack.eventDetail.edit',
    toggleComplete: 'ontrack.eventDetail.toggleComplete',
    close: 'ontrack.eventDetail.close',
    backdrop: 'ontrack.eventDetail.backdrop',
    fightCard: 'ontrack.eventDetail.section.fightCard',
    fightCardTab: (section: string) => `ontrack.eventDetail.fightCard.tab.${section}`,
    fightCardBout: (boutId: string) =>
      `ontrack.eventDetail.fightCard.bout.${boutId.replace(/[^a-zA-Z0-9]+/g, '_')}`,
    fightCardModal: 'ontrack.eventDetail.fightCard.modal',
    metadata: 'ontrack.eventDetail.section.metadata',
    ticket: 'ontrack.eventDetail.ticket',
  },
  activityForm: {
    choice: (group: string, value: string) => `ontrack.activityForm.choice.${group}.${value}`,
    category: (categoryId: string) => `ontrack.activityForm.category.${categoryId}`,
    guidedTitle: 'ontrack.activityForm.guidedTitle',
    title: 'ontrack.activityForm.title',
    scheduleSection: 'ontrack.activityForm.section.schedule',
    date: 'ontrack.activityForm.date',
    durationHours: 'ontrack.activityForm.duration.hours',
    durationMinutes: 'ontrack.activityForm.duration.mins',
    startTime: 'ontrack.activityForm.startTime',
    notes: 'ontrack.activityForm.notes',
    attendeeEmails: 'ontrack.activityForm.attendeeEmails',
    pickPhoto: 'ontrack.activityForm.pickPhoto',
    analyzePhoto: 'ontrack.activityForm.analyzePhoto',
    removePhoto: 'ontrack.activityForm.removePhoto',
    save: 'ontrack.activityForm.save',
    saveThisOccurrence: 'ontrack.activityForm.saveThisOccurrence',
    saveSeries: 'ontrack.activityForm.saveSeries',
    /** Swipe-down / tap affordance at the top of the modal. */
    grabber: 'ontrack.activityForm.grabber',
    backdrop: 'ontrack.activityForm.backdrop',
    cancel: 'ontrack.activityForm.cancel',
    delete: 'ontrack.activityForm.delete',
    event: {
      tabs: 'ontrack.activityForm.event.tabs',
      search: 'ontrack.activityForm.event.search',
      sportFilter: 'ontrack.activityForm.event.sportFilter',
      sportOption: (sport: string) => `ontrack.activityForm.event.sportFilter.${sport}`,
      upcoming: 'ontrack.activityForm.event.section.upcoming',
      followTargets: 'ontrack.activityForm.event.section.followTargets',
      result: (provider: string, id: string) =>
        `ontrack.activityForm.event.result.${provider}.${id}`,
      followTarget: (provider: string, id: string) =>
        `ontrack.activityForm.event.followTarget.${provider}.${id}`,
      followModeReview: 'ontrack.activityForm.event.followMode.review',
      followModeAuto: 'ontrack.activityForm.event.followMode.auto',
      loadMore: 'ontrack.activityForm.event.loadMore',
      refresh: 'ontrack.activityForm.event.refresh',
      follow: (id: string) => `ontrack.activityForm.event.follow.${id}`,
      unfollow: (id: string) => `ontrack.activityForm.event.unfollow.${id}`,
      suggestion: (id: string) => `ontrack.activityForm.event.suggestion.${id}`,
      acceptSuggestion: (id: string) => `ontrack.activityForm.event.suggestion.${id}.accept`,
      dismissSuggestion: (id: string) => `ontrack.activityForm.event.suggestion.${id}.dismiss`,
      selected: 'ontrack.activityForm.event.section.selected',
      changeSelection: 'ontrack.activityForm.event.changeSelection',
      following: 'ontrack.activityForm.event.section.following',
      suggestions: 'ontrack.activityForm.event.section.suggestions',
    },
  },
  apiUsage: {
    screen: 'ontrack.apiUsage.screen',
    back: 'ontrack.apiUsage.back',
    /** Reloads the integrations health snapshot. */
    sync: 'ontrack.apiUsage.sync',
    /** @deprecated Use `sync`. */
    refresh: 'ontrack.apiUsage.sync',
    retry: 'ontrack.apiUsage.retry',
    healthSummary: 'ontrack.apiUsage.healthSummary',
    /** Opens the sort dropdown sheet. */
    sort: 'ontrack.apiUsage.sort',
    sortOption: (mode: string) => `ontrack.apiUsage.sort.${mode}`,
    service: (serviceId: string) => `ontrack.apiUsage.service.${serviceId}`,
  },
  developer: {
    back: 'ontrack.developer.back',
    section: {
      appUpdates: 'ontrack.developer.section.appUpdates',
      navigate: 'ontrack.developer.section.navigate',
      insights: 'ontrack.developer.section.insights',
      runtime: 'ontrack.developer.section.runtime',
      diagnostics: 'ontrack.developer.section.diagnostics',
      tools: 'ontrack.developer.section.tools',
    },
    insights: 'ontrack.developer.insights',
    insightsLocal: 'ontrack.developer.insights.local',
    insightsProduct: 'ontrack.developer.insights.product',
    insightsRefresh: 'ontrack.developer.insights.refresh',
    releaseNotes: 'ontrack.developer.releaseNotes',
    releaseNotesCurrentVersion: 'ontrack.developer.releaseNotes.currentVersion',
    releaseNotesTabs: 'ontrack.developer.releaseNotes.tabs',
    releaseNotesTab: (tab: string) => `ontrack.developer.releaseNotes.tab.${tab}`,
    releaseNotesList: 'ontrack.developer.releaseNotes.list',
    releaseNotesDay: (date: string) => `ontrack.developer.releaseNotes.day.${date}`,
    releaseNotesVersion: (version: string) => `ontrack.developer.releaseNotes.version.${version}`,
    releaseNotesDate: 'ontrack.developer.releaseNotes.date',
    releaseNotesPrev: 'ontrack.developer.releaseNotes.prev',
    releaseNotesNext: 'ontrack.developer.releaseNotes.next',
    devMode: 'ontrack.developer.devMode',
    staySignedIn: 'ontrack.developer.staySignedIn',
    lockSession: 'ontrack.developer.lockSession',
    designSystem: 'ontrack.developer.designSystem',
    apiUsage: 'ontrack.developer.apiUsage',
    performance: 'ontrack.developer.performance',
    env: 'ontrack.developer.env',
    overlay: 'ontrack.developer.overlay',
    sync: 'ontrack.developer.sync',
    seeds: 'ontrack.developer.seeds',
    seed: (name: string) => `ontrack.developer.seed.${name}`,
    routeInput: 'ontrack.developer.routeInput',
    routeGo: 'ontrack.developer.routeGo',
    storage: 'ontrack.developer.storage',
    storageRefresh: 'ontrack.developer.storageRefresh',
    rateLimitReset: 'ontrack.developer.rateLimitReset',
  },
  performance: {
    back: 'ontrack.performance.back',
    unsupported: 'ontrack.performance.unsupported',
    processDetails: 'ontrack.performance.processDetails',
    copy: 'ontrack.performance.copy',
    settings: 'ontrack.performance.settings',
    clear: 'ontrack.performance.clear',
    clearConfirm: 'ontrack.performance.clear.confirm',
    filter: (filter: string) => `ontrack.performance.filter.${filter}`,
    activity: (id: string) => `ontrack.performance.activity.${id}`,
    section: {
      live: 'ontrack.performance.section.live',
      warnings: 'ontrack.performance.section.warnings',
      activities: 'ontrack.performance.section.activities',
      history: 'ontrack.performance.section.history',
      tools: 'ontrack.performance.section.tools',
    },
  },
  designSystem: {
    back: 'ontrack.designSystem.back',
    info: 'ontrack.designSystem.info',
    mode: (mode: string) => `ontrack.designSystem.mode.${mode}`,
    catalogGroup: (group: string) => `ontrack.designSystem.catalogGroup.${group}`,
    catalogElement: (id: string) => `ontrack.designSystem.catalogElement.${id}`,
    demo: (name: string) => `ontrack.designSystem.demo.${name}`,
    primary: 'ontrack.designSystem.primary',
    secondary: 'ontrack.designSystem.secondary',
    ghost: 'ontrack.designSystem.ghost',
    delete: 'ontrack.designSystem.delete',
    input: 'ontrack.designSystem.input',
    sheetClose: 'ontrack.designSystem.sheet.close',
    section: (scope: string) => `ontrack.designSystem.section.${scope}`,
    token: (scope: string, key: string) => `ontrack.designSystem.token.${scope}.${key}`,
    resetToken: (scope: string, key: string) => `ontrack.designSystem.resetToken.${scope}.${key}`,
    preset: (scope: string, key: string, hex: string) =>
      `ontrack.designSystem.preset.${scope}.${key}.${hex.replace('#', '').toLowerCase()}`,
    resetAll: 'ontrack.designSystem.resetAll',
    resetAllFooter: 'ontrack.designSystem.resetAll.footer',
    confirmRestoreDefaults: 'ontrack.designSystem.confirmRestoreDefaults',
    historySection: 'ontrack.designSystem.history',
    historyEntry: (id: string) => `ontrack.designSystem.history.entry.${id}`,
    clearHistory: 'ontrack.designSystem.history.clear',
    swatch: (scope: string, key: string) => `ontrack.designSystem.swatch.${scope}.${key}`,
    iconSection: (section: string) => `ontrack.designSystem.iconSection.${section}`,
    icon: (name: string) => `ontrack.designSystem.icon.${name}`,
    fontRole: (role: string) => `ontrack.designSystem.fontRole.${role}`,
    fontPreset: (role: string, id: string) => `ontrack.designSystem.fontPreset.${role}.${id}`,
    fontScale: 'ontrack.designSystem.fontScale',
    resetFonts: 'ontrack.designSystem.resetFonts',
    confirmRestoreFonts: 'ontrack.designSystem.confirmRestoreFonts',
  },
  social: {
    friendInvite: {
      signIn: 'ontrack.social.friendInvite.signIn',
      accept: 'ontrack.social.friendInvite.accept',
      notNow: 'ontrack.social.friendInvite.notNow',
      openSocial: 'ontrack.social.friendInvite.openSocial',
      section: {
        card: 'ontrack.social.friendInvite.section.card',
      },
    },
    header: {
      addFriend: 'ontrack.social.header.addFriend',
      messages: 'ontrack.social.header.messages',
    },
    friends: {
      close: 'ontrack.social.friends.close',
      signIn: 'ontrack.social.friends.signIn',
      seeAll: 'ontrack.social.friends.seeAll',
      add: 'ontrack.social.friends.add',
      openInviteTools: 'ontrack.social.friends.openInviteTools',
      inviteToolsClose: 'ontrack.social.friends.inviteTools.close',
      emptyAdd: 'ontrack.social.friends.empty.add',
      listSection: 'ontrack.social.friends.section.list',
      friend: (friendId: string) => `ontrack.social.friends.friend.${friendId}`,
    },
    quickAction: (actionId: string) => `ontrack.social.quickAction.${actionId}`,
    upcoming: {
      seeAll: 'ontrack.social.upcoming.seeAll',
      empty: 'ontrack.social.upcoming.empty',
      trip: (tripId: string) => `ontrack.social.upcoming.trip.${tripId}`,
    },
    feedFilter: (filter: string) => `ontrack.social.feed.filter.${filter}`,
    feedItem: (itemId: string) => `ontrack.social.feed.item.${itemId}`,
    feedPollChoice: (itemId: string, choiceId: string) =>
      `ontrack.social.feed.poll.${itemId}.${choiceId}`,
    feedLoadMore: 'ontrack.social.feed.loadMore',
    actionModal: {
      close: 'ontrack.social.actionModal.close',
      primary: 'ontrack.social.actionModal.primary',
    },
    inviteSlug: 'ontrack.social.invite.slug',
    inviteSave: 'ontrack.social.invite.save',
    inviteCopy: 'ontrack.social.invite.copy',
    inviteShare: 'ontrack.social.invite.share',
    friendEmail: 'ontrack.social.friend.email',
    friendSend: 'ontrack.social.friend.send',
    requestAccept: (requestId: string) => `ontrack.social.request.accept.${requestId}`,
    requestDecline: (requestId: string) => `ontrack.social.request.decline.${requestId}`,
    requestCancel: (requestId: string) => `ontrack.social.request.cancel.${requestId}`,
    friendAddToTrip: (friendId: string) => `ontrack.social.friend.addToTrip.${friendId}`,
    friendRemove: (friendId: string) => `ontrack.social.friend.remove.${friendId}`,
    friendBlock: (friendId: string) => `ontrack.social.friend.block.${friendId}`,
    friendReport: (friendId: string) => `ontrack.social.friend.report.${friendId}`,
  },
  chrome: {
    back: 'ontrack.chrome.back',
    headerBack: 'ontrack.chrome.headerBack',
  },
  errorBoundary: {
    root: 'ontrack.errorBoundary.root',
    retry: 'ontrack.errorBoundary.retry',
    sendReport: 'ontrack.errorBoundary.sendReport',
    reportStatus: 'ontrack.errorBoundary.reportStatus',
  },
  agentUi: {
    /** __DEV__ overlay root — present when AgentUiOverlay is mounted. */
    overlayRoot: 'ontrack.agentUi.overlay.root',
    /** Floating per-page overlay toggle (Dev Mode). */
    overlayToggle: 'ontrack.agentUi.overlay.toggle',
  },
  dev: {
    /** __DEV__ floating Light/Dark switcher — triple-tap page to show/hide. */
    themeToggle: 'ontrack.dev.themeToggle',
  },
} as const;
