/** Finance agent-ui testIDs (composed into AgentUiIds). */

export const agentUiIdsFinance = {
  finance: {
    screen: 'ontrack.finance.hub',
    /** Compact eyebrow back on Finance nested screens. */
    back: 'ontrack.finance.back',
    section: (name: string) => `ontrack.finance.section.${name}`,
    addExpense: 'ontrack.finance.hub.addExpense',
    openTransactions: 'ontrack.finance.hub.transactions',
    openBills: 'ontrack.finance.hub.bills',
    openBuckets: 'ontrack.finance.hub.buckets',
    openEntities: 'ontrack.finance.hub.entities',
    openTax: 'ontrack.finance.hub.tax',
    openAccounts: 'ontrack.finance.hub.accounts',
    markBillPaid: (id: string) => `ontrack.finance.hub.billPaid.${id}`,
    coachCard: (id: string) => `ontrack.finance.coach.${id}`,
    credit: {
      card: 'ontrack.finance.credit.card',
      edit: 'ontrack.finance.credit.edit',
      score: 'ontrack.finance.credit.score',
      bureau: (id: string) => `ontrack.finance.credit.bureau.${id}`,
      model: (id: string) => `ontrack.finance.credit.model.${id}`,
      asOf: 'ontrack.finance.credit.asOf',
      save: 'ontrack.finance.credit.save',
      close: 'ontrack.finance.credit.close',
      provider: (id: string) => `ontrack.finance.credit.provider.${id}`,
    },
    expense: {
      form: 'ontrack.finance.expense.form',
      merchant: 'ontrack.finance.expense.merchant',
      amount: 'ontrack.finance.expense.amount',
      date: 'ontrack.finance.expense.date',
      category: (id: string) => `ontrack.finance.expense.category.${id}`,
      entity: (id: string) => `ontrack.finance.expense.entity.${id}`,
      notes: 'ontrack.finance.expense.notes',
      save: 'ontrack.finance.expense.save',
      cancel: 'ontrack.finance.expense.cancel',
    },
    transactions: {
      screen: 'ontrack.finance.transactions',
      row: (id: string) => `ontrack.finance.transactions.row.${id}`,
      add: 'ontrack.finance.transactions.add',
    },
    bills: {
      screen: 'ontrack.finance.bills',
      add: 'ontrack.finance.bills.add',
      row: (id: string) => `ontrack.finance.bills.row.${id}`,
      markPaid: (id: string) => `ontrack.finance.bills.paid.${id}`,
      name: 'ontrack.finance.bills.name',
      amount: 'ontrack.finance.bills.amount',
      kind: (kind: string) => `ontrack.finance.bills.kind.${kind}`,
      save: 'ontrack.finance.bills.save',
    },
    buckets: {
      screen: 'ontrack.finance.buckets',
      add: 'ontrack.finance.buckets.add',
      row: (id: string) => `ontrack.finance.buckets.row.${id}`,
      name: 'ontrack.finance.buckets.name',
      goal: 'ontrack.finance.buckets.goal',
      contribute: 'ontrack.finance.buckets.contribute',
      contributeAmount: 'ontrack.finance.buckets.contributeAmount',
      save: 'ontrack.finance.buckets.save',
    },
    entities: {
      screen: 'ontrack.finance.entities',
      add: 'ontrack.finance.entities.add',
      row: (id: string) => `ontrack.finance.entities.row.${id}`,
      name: 'ontrack.finance.entities.name',
      kind: (kind: string) => `ontrack.finance.entities.kind.${kind}`,
      save: 'ontrack.finance.entities.save',
    },
    accounts: {
      screen: 'ontrack.finance.accounts',
      addManual: 'ontrack.finance.accounts.addManual',
      linkBank: 'ontrack.finance.accounts.linkBank',
      plaidMigration: 'ontrack.finance.accounts.plaidMigration',
      retirePlaidBanks: 'ontrack.finance.accounts.retirePlaidBanks',
      confirmPlaidMigration: 'ontrack.finance.accounts.confirmPlaidMigration',
      row: (id: string) => `ontrack.finance.accounts.row.${id}`,
      name: 'ontrack.finance.accounts.name',
      last4: 'ontrack.finance.accounts.last4',
      apr: 'ontrack.finance.accounts.apr',
      save: 'ontrack.finance.accounts.save',
      savingsApr: 'ontrack.finance.accounts.savingsApr',
      sync: (id: string) => `ontrack.finance.accounts.sync.${id}`,
      disconnect: (id: string) => `ontrack.finance.accounts.disconnect.${id}`,
      confirmDisconnect: (id: string) => `ontrack.finance.accounts.confirmDisconnect.${id}`,
      linkInvestments: 'ontrack.finance.accounts.linkInvestments',
      balance: 'ontrack.finance.accounts.balance',
    },
    tax: {
      screen: 'ontrack.finance.tax',
      ensureYear: 'ontrack.finance.tax.ensureYear',
      checklist: (key: string) => `ontrack.finance.tax.checklist.${key}`,
      export: 'ontrack.finance.tax.export',
      fileElsewhere: 'ontrack.finance.tax.fileElsewhere',
      handoff: (id: string) => `ontrack.finance.tax.handoff.${id}`,
      handoffClose: 'ontrack.finance.tax.handoff.close',
      customUrl: 'ontrack.finance.tax.customUrl',
      uploadDoc: 'ontrack.finance.tax.uploadDoc',
      entity: (id: string) => `ontrack.finance.tax.entity.${id}`,
    },
  },
} as const;
