/** Finance agent-ui testIDs (composed into AgentUiIds). */

export const agentUiIdsFinance = {
  finance: {
    screen: 'ontrack.finance.hub',
    /** Compact eyebrow back on Finance nested screens. */
    back: 'ontrack.finance.back',
    section: (name: string) => `ontrack.finance.section.${name}`,
    openTransactions: 'ontrack.finance.hub.transactions',
    openBills: 'ontrack.finance.hub.bills',
    openSubscriptions: 'ontrack.finance.hub.subscriptions',
    openRecurring: 'ontrack.finance.hub.recurring',
    openBuckets: 'ontrack.finance.hub.buckets',
    openEntities: 'ontrack.finance.hub.entities',
    openTax: 'ontrack.finance.hub.tax',
    openRewards: 'ontrack.finance.hub.rewards',
    openAccounts: 'ontrack.finance.hub.accounts',
    openEzPass: 'ontrack.finance.hub.ezpass',
    markBillPaid: (id: string) => `ontrack.finance.hub.billPaid.${id}`,
    coachCard: (id: string) => `ontrack.finance.coach.${id}`,
    credit: {
      card: 'ontrack.finance.credit.card',
      edit: 'ontrack.finance.credit.edit',
      score: 'ontrack.finance.credit.score',
      bureau: (id: string) => `ontrack.finance.credit.bureau.${id}`,
      model: (id: string) => `ontrack.finance.credit.model.${id}`,
      asOf: 'ontrack.finance.credit.asOf',
      save: 'ontrack.finance.credit.save',
      close: 'ontrack.finance.credit.close',
      provider: (id: string) => `ontrack.finance.credit.provider.${id}`,
    },
    expense: {
      form: 'ontrack.finance.expense.form',
      merchant: 'ontrack.finance.expense.merchant',
      amount: 'ontrack.finance.expense.amount',
      date: 'ontrack.finance.expense.date',
      category: (id: string) => `ontrack.finance.expense.category.${id}`,
      entity: (id: string) => `ontrack.finance.expense.entity.${id}`,
      notes: 'ontrack.finance.expense.notes',
      save: 'ontrack.finance.expense.save',
      cancel: 'ontrack.finance.expense.cancel',
    },
    transactions: {
      screen: 'ontrack.finance.transactions',
      activitySection: 'ontrack.finance.transactions.section.activity',
      dateGroup: (date: string) => `ontrack.finance.transactions.date.${date}`,
      search: 'ontrack.finance.transactions.search',
      categoryFilter: 'ontrack.finance.transactions.filter.categories',
      categoryFilterOption: (id: string) =>
        `ontrack.finance.transactions.filter.category.${id}`,
      sort: 'ontrack.finance.transactions.sort',
      sortOption: (id: string) => `ontrack.finance.transactions.sort.${id}`,
      row: (id: string) => `ontrack.finance.transactions.row.${id}`,
      add: 'ontrack.finance.transactions.add',
      categorySheet: 'ontrack.finance.transactions.category.sheet',
      categoryClose: 'ontrack.finance.transactions.category.close',
      categoryBackdrop: 'ontrack.finance.transactions.category.backdrop',
      categorySelector: 'ontrack.finance.transactions.category.selector',
      category: (id: string) => `ontrack.finance.transactions.category.${id}`,
      newCategoryName: 'ontrack.finance.transactions.category.newName',
      createCategory: 'ontrack.finance.transactions.category.create',
      categorySave: 'ontrack.finance.transactions.category.save',
    },
    ezpass: {
      screen: 'ontrack.finance.ezpass',
      home: 'ontrack.finance.ezpass.home',
      summary: 'ontrack.finance.ezpass.summary',
      monthChart: 'ontrack.finance.ezpass.monthChart',
      monthDetail: 'ontrack.finance.ezpass.monthDetail',
      month: (key: string) => `ontrack.finance.ezpass.month.${key}`,
      driverFilter: (value: string) => `ontrack.finance.ezpass.driver.${value}`,
      friendTag: (id: string) => `ontrack.finance.ezpass.friendTag.${id}`,
      assignSelf: 'ontrack.finance.ezpass.assignSelf',
      memberManagement: 'ontrack.finance.ezpass.memberManagement',
      memberRole: (id: string) => `ontrack.finance.ezpass.memberRole.${id}`,
      memberRemove: (id: string) => `ontrack.finance.ezpass.memberRemove.${id}`,
      memberConfirmRemove: (id: string) =>
        `ontrack.finance.ezpass.memberConfirmRemove.${id}`,
      share: 'ontrack.finance.ezpass.share',
      ledger: (id: string) => `ontrack.finance.ezpass.ledger.${id}`,
      upload: 'ontrack.finance.ezpass.upload',
      statements: 'ontrack.finance.ezpass.statements',
      statementsToggle: 'ontrack.finance.ezpass.statements.toggle',
      statement: (id: string) => `ontrack.finance.ezpass.statement.${id}`,
      emptyUpload: 'ontrack.finance.ezpass.emptyUpload',
      roadActivity: 'ontrack.finance.ezpass.roadActivity',
      replenishments: 'ontrack.finance.ezpass.replenishments',
      day: (date: string) => `ontrack.finance.ezpass.day.${date}`,
      activityRow: (id: string) => `ontrack.finance.ezpass.activity.${id}`,
      officialSite: 'ontrack.finance.ezpass.officialSite',
      file: 'ontrack.finance.ezpass.file',
      screenshots: 'ontrack.finance.ezpass.screenshots',
      ai: 'ontrack.finance.ezpass.ai',
      category: (id: string) => `ontrack.finance.ezpass.category.${id}`,
      row: (id: string) => `ontrack.finance.ezpass.row.${id}`,
      confirm: 'ontrack.finance.ezpass.confirm',
    },
    bills: {
      screen: 'ontrack.finance.bills',
      add: 'ontrack.finance.bills.add',
      row: (id: string) => `ontrack.finance.bills.row.${id}`,
      remove: (id: string) => `ontrack.finance.bills.remove.${id}`,
      confirmRemove: (id: string) => `ontrack.finance.bills.confirmRemove.${id}`,
      name: 'ontrack.finance.bills.name',
      amount: 'ontrack.finance.bills.amount',
      kind: (kind: string) => `ontrack.finance.bills.kind.${kind}`,
      save: 'ontrack.finance.bills.save',
    },
    subscriptions: {
      screen: 'ontrack.finance.subscriptions',
      addManual: 'ontrack.finance.subscriptions.addManual',
      form: 'ontrack.finance.subscriptions.form',
      formClose: 'ontrack.finance.subscriptions.form.close',
      formBackdrop: 'ontrack.finance.subscriptions.form.backdrop',
      refresh: 'ontrack.finance.subscriptions.refresh',
      refreshStatus: 'ontrack.finance.subscriptions.refreshStatus',
      dismissRefreshStatus: 'ontrack.finance.subscriptions.refreshStatus.dismiss',
      candidate: (id: string) => `ontrack.finance.subscriptions.candidate.${id}`,
      confirm: (id: string) => `ontrack.finance.subscriptions.confirm.${id}`,
      dismiss: (id: string) => `ontrack.finance.subscriptions.dismiss.${id}`,
      row: (id: string) => `ontrack.finance.subscriptions.row.${id}`,
      remove: (id: string) => `ontrack.finance.subscriptions.remove.${id}`,
      confirmRemove: (id: string) => `ontrack.finance.subscriptions.confirmRemove.${id}`,
      name: 'ontrack.finance.subscriptions.name',
      amount: 'ontrack.finance.subscriptions.amount',
      nextDue: 'ontrack.finance.subscriptions.nextDue',
      cadence: 'ontrack.finance.subscriptions.cadence',
      save: 'ontrack.finance.subscriptions.save',
    },
    recurring: {
      screen: 'ontrack.finance.recurring',
      add: 'ontrack.finance.recurring.add',
      form: 'ontrack.finance.recurring.form',
      formClose: 'ontrack.finance.recurring.form.close',
      formBackdrop: 'ontrack.finance.recurring.form.backdrop',
      type: (type: string) => `ontrack.finance.recurring.type.${type}`,
      billKind: 'ontrack.finance.recurring.billKind',
      name: 'ontrack.finance.recurring.name',
      amount: 'ontrack.finance.recurring.amount',
      apr: 'ontrack.finance.recurring.apr',
      cadence: 'ontrack.finance.recurring.cadence',
      nextDue: 'ontrack.finance.recurring.nextDue',
      entity: 'ontrack.finance.recurring.entity',
      save: 'ontrack.finance.recurring.save',
      categorize: (id: string) => `ontrack.finance.recurring.categorize.${id}`,
      categorizeSheet: 'ontrack.finance.recurring.categorize.sheet',
      categorizeClose: 'ontrack.finance.recurring.categorize.close',
      categorizeBackdrop: 'ontrack.finance.recurring.categorize.backdrop',
      categorizeType: (type: string) => `ontrack.finance.recurring.categorize.type.${type}`,
      categorizeName: 'ontrack.finance.recurring.categorize.name',
      categorizeBillKind: 'ontrack.finance.recurring.categorize.billKind',
      categorizeSave: 'ontrack.finance.recurring.categorize.save',
    },
    buckets: {
      screen: 'ontrack.finance.buckets',
      add: 'ontrack.finance.buckets.add',
      row: (id: string) => `ontrack.finance.buckets.row.${id}`,
      name: 'ontrack.finance.buckets.name',
      goal: 'ontrack.finance.buckets.goal',
      contribute: 'ontrack.finance.buckets.contribute',
      contributeAmount: 'ontrack.finance.buckets.contributeAmount',
      save: 'ontrack.finance.buckets.save',
    },
    entities: {
      screen: 'ontrack.finance.entities',
      add: 'ontrack.finance.entities.add',
      row: (id: string) => `ontrack.finance.entities.row.${id}`,
      name: 'ontrack.finance.entities.name',
      kind: (kind: string) => `ontrack.finance.entities.kind.${kind}`,
      save: 'ontrack.finance.entities.save',
    },
    accounts: {
      screen: 'ontrack.finance.accounts',
      addManual: 'ontrack.finance.accounts.addManual',
      linkBank: 'ontrack.finance.accounts.linkBank',
      row: (id: string) => `ontrack.finance.accounts.row.${id}`,
      name: 'ontrack.finance.accounts.name',
      last4: 'ontrack.finance.accounts.last4',
      apr: 'ontrack.finance.accounts.apr',
      save: 'ontrack.finance.accounts.save',
      savingsApr: 'ontrack.finance.accounts.savingsApr',
      sync: (id: string) => `ontrack.finance.accounts.sync.${id}`,
      disconnect: (id: string) => `ontrack.finance.accounts.disconnect.${id}`,
      confirmDisconnect: (id: string) => `ontrack.finance.accounts.confirmDisconnect.${id}`,
      linkInvestments: 'ontrack.finance.accounts.linkInvestments',
      balance: 'ontrack.finance.accounts.balance',
      rewardProfile: (id: string) => `ontrack.finance.accounts.rewardProfile.${id}`,
    },
    rewards: {
      screen: 'ontrack.finance.rewards',
      hero: 'ontrack.finance.rewards.section.hero',
      profilesSection: 'ontrack.finance.rewards.section.profiles',
      transactionsSection: 'ontrack.finance.rewards.section.transactions',
      compareSection: 'ontrack.finance.rewards.section.compare',
      addManual: 'ontrack.finance.rewards.addManual',
      createFromLink: 'ontrack.finance.rewards.createFromLink',
      importCsv: 'ontrack.finance.rewards.importCsv',
      range: (value: string) => `ontrack.finance.rewards.range.${value}`,
      customFrom: 'ontrack.finance.rewards.customFrom',
      customTo: 'ontrack.finance.rewards.customTo',
      profile: (id: string) => `ontrack.finance.rewards.profile.${id}`,
      transaction: (id: string) => `ontrack.finance.rewards.transaction.${id}`,
      compareLeft: 'ontrack.finance.rewards.compare.left',
      compareRight: 'ontrack.finance.rewards.compare.right',
      profileSheet: 'ontrack.finance.rewards.profile.sheet',
      profileClose: 'ontrack.finance.rewards.profile.close',
      profileBackdrop: 'ontrack.finance.rewards.profile.backdrop',
      profileSave: 'ontrack.finance.rewards.profile.save',
      profileName: 'ontrack.finance.rewards.profile.name',
      profileIssuer: 'ontrack.finance.rewards.profile.issuer',
      profileNetwork: 'ontrack.finance.rewards.profile.network',
      profileOwnership: (value: string) => `ontrack.finance.rewards.profile.ownership.${value}`,
      profileCurrency: 'ontrack.finance.rewards.profile.currency',
      profileBaseRate: 'ontrack.finance.rewards.profile.baseRate',
      profilePointValue: 'ontrack.finance.rewards.profile.pointValue',
      profileAnnualFee: 'ontrack.finance.rewards.profile.annualFee',
      ruleAdd: 'ontrack.finance.rewards.rule.add',
      ruleName: (id: string) => `ontrack.finance.rewards.rule.${id}.name`,
      ruleRate: (id: string) => `ontrack.finance.rewards.rule.${id}.rate`,
      ruleCategories: (id: string) => `ontrack.finance.rewards.rule.${id}.categories`,
      ruleSourceCategories: (id: string) => `ontrack.finance.rewards.rule.${id}.sourceCategories`,
      ruleCap: (id: string) => `ontrack.finance.rewards.rule.${id}.cap`,
      ruleCapPeriod: (id: string) => `ontrack.finance.rewards.rule.${id}.capPeriod`,
      ruleCapGroup: (id: string) => `ontrack.finance.rewards.rule.${id}.capGroup`,
      ruleStartsOn: (id: string) => `ontrack.finance.rewards.rule.${id}.startsOn`,
      ruleEndsOn: (id: string) => `ontrack.finance.rewards.rule.${id}.endsOn`,
      ruleActive: (id: string) => `ontrack.finance.rewards.rule.${id}.active`,
      ruleRemove: (id: string) => `ontrack.finance.rewards.rule.${id}.remove`,
      benefitAdd: 'ontrack.finance.rewards.benefit.add',
      benefitName: (id: string) => `ontrack.finance.rewards.benefit.${id}.name`,
      benefitFaceValue: (id: string) => `ontrack.finance.rewards.benefit.${id}.faceValue`,
      benefitUserValue: (id: string) => `ontrack.finance.rewards.benefit.${id}.userValue`,
      benefitEnabled: (id: string) => `ontrack.finance.rewards.benefit.${id}.enabled`,
      benefitRemove: (id: string) => `ontrack.finance.rewards.benefit.${id}.remove`,
      welcomeOffer: 'ontrack.finance.rewards.welcomeOffer',
      welcomeRewardAmount: 'ontrack.finance.rewards.welcomeRewardAmount',
      welcomeSpendRequirement: 'ontrack.finance.rewards.welcomeSpendRequirement',
      welcomeMonths: 'ontrack.finance.rewards.welcomeMonths',
      linkSheet: 'ontrack.finance.rewards.link.sheet',
      linkClose: 'ontrack.finance.rewards.link.close',
      linkBackdrop: 'ontrack.finance.rewards.link.backdrop',
      linkUrl: 'ontrack.finance.rewards.link.url',
      linkAnalyze: 'ontrack.finance.rewards.link.analyze',
      csvSheet: 'ontrack.finance.rewards.csv.sheet',
      csvClose: 'ontrack.finance.rewards.csv.close',
      csvBackdrop: 'ontrack.finance.rewards.csv.backdrop',
      csvChoose: 'ontrack.finance.rewards.csv.choose',
      csvAccount: 'ontrack.finance.rewards.csv.account',
      csvDate: 'ontrack.finance.rewards.csv.date',
      csvMerchant: 'ontrack.finance.rewards.csv.merchant',
      csvAmount: 'ontrack.finance.rewards.csv.amount',
      csvCategory: 'ontrack.finance.rewards.csv.category',
      csvImport: 'ontrack.finance.rewards.csv.import',
    },
    tax: {
      screen: 'ontrack.finance.tax',
      ensureYear: 'ontrack.finance.tax.ensureYear',
      checklist: (key: string) => `ontrack.finance.tax.checklist.${key}`,
      export: 'ontrack.finance.tax.export',
      fileElsewhere: 'ontrack.finance.tax.fileElsewhere',
      handoff: (id: string) => `ontrack.finance.tax.handoff.${id}`,
      handoffClose: 'ontrack.finance.tax.handoff.close',
      customUrl: 'ontrack.finance.tax.customUrl',
      uploadDoc: 'ontrack.finance.tax.uploadDoc',
      entity: (id: string) => `ontrack.finance.tax.entity.${id}`,
    },
  },
} as const;
