import type { TextStyle } from 'react-native';

import type { TravelTimelineNodeProps } from '@/features/travel/travel-timeline-node-props';
import type { TravelItineraryItem } from '@/features/travel/types';
import type { AgentUiTarget } from '@/utils/agent-ui';

type FlightCaption = {
  dateLabel?: string;
  durationLabel?: string;
  stopsLabel?: string;
};

export type TravelTimelineNodeBodyProps = {
  item: TravelItineraryItem;
  isExpanded: boolean;
  dense: boolean;
  compact: boolean;
  isCompactBoardCard: boolean;
  isCompactFlight: boolean;
  isMoment: boolean;
  isStructuredTravelKind: boolean;
  title: string;
  caption: string | undefined;
  flightCaption: FlightCaption | undefined;
  shareCue: string | undefined;
  photos: string[];
  icon: string;
  accent: string;
  onGlass: boolean;
  primaryInk: string;
  secondaryInk: string;
  tertiaryInk: string;
  mistProps: Record<string, unknown>;
  showKindBadgeResolved: boolean;
  showHeaderCaption: boolean;
  showDenseMeta: boolean;
  showStructuredDetails: boolean;
  allowStructuredEditing: boolean;
  hasDenseTimeSlot: boolean;
  leadingTimeLabel?: string;
  denseTimeWidth: number;
  denseIconGap: number;
  denseDetailsInset: number;
  denseChromeTextStyle: TextStyle;
  kindPillSize: number;
  boardIconSize: number;
  compactActionSize: number;
  toolbarActionSize: number;
  collapsedBoardMinHeight: number;
  rs: { md: number; sm: number; xs: number; xxs: number };
  s: (n: number) => number;
  toggleAgent: AgentUiTarget;
  addressAgent: AgentUiTarget;
  onToggle: () => void;
  editingFlight: boolean;
  editingRental: boolean;
  editingStay: boolean;
  editingTransport: boolean;
  editingStructured: boolean;
  dateDisplayFormat: TravelTimelineNodeProps['dateDisplayFormat'];
  editedFlightDetails: TravelTimelineNodeProps['editedFlightDetails'];
  editedFlightDetailsError: TravelTimelineNodeProps['editedFlightDetailsError'];
  editedFlightFileName: TravelTimelineNodeProps['editedFlightFileName'];
  importingFlight: TravelTimelineNodeProps['importingFlight'];
  editedRentalDetails: TravelTimelineNodeProps['editedRentalDetails'];
  editedRentalDetailsError: TravelTimelineNodeProps['editedRentalDetailsError'];
  editedRentalFileName: TravelTimelineNodeProps['editedRentalFileName'];
  importingRental: TravelTimelineNodeProps['importingRental'];
  editedStayDetails: TravelTimelineNodeProps['editedStayDetails'];
  editedStayDetailsError: TravelTimelineNodeProps['editedStayDetailsError'];
  editedStayFileName: TravelTimelineNodeProps['editedStayFileName'];
  importingStay: TravelTimelineNodeProps['importingStay'];
  planStartDate: TravelTimelineNodeProps['planStartDate'];
  planEndDate: TravelTimelineNodeProps['planEndDate'];
  onEditedFlightDetailsChange: TravelTimelineNodeProps['onEditedFlightDetailsChange'];
  onImportFlight: TravelTimelineNodeProps['onImportFlight'];
  onSaveFlightDetails: TravelTimelineNodeProps['onSaveFlightDetails'];
  onCancelFlightEdit: TravelTimelineNodeProps['onCancelFlightEdit'];
  onBeginFlightEdit: TravelTimelineNodeProps['onBeginFlightEdit'];
  onEditedRentalDetailsChange: TravelTimelineNodeProps['onEditedRentalDetailsChange'];
  onImportRental: TravelTimelineNodeProps['onImportRental'];
  onSaveRentalDetails: TravelTimelineNodeProps['onSaveRentalDetails'];
  onCancelRentalEdit: TravelTimelineNodeProps['onCancelRentalEdit'];
  onBeginRentalEdit: TravelTimelineNodeProps['onBeginRentalEdit'];
  onEditedStayDetailsChange: TravelTimelineNodeProps['onEditedStayDetailsChange'];
  onImportStay: TravelTimelineNodeProps['onImportStay'];
  onSaveStayDetails: TravelTimelineNodeProps['onSaveStayDetails'];
  onCancelStayEdit: TravelTimelineNodeProps['onCancelStayEdit'];
  onBeginStayEdit: TravelTimelineNodeProps['onBeginStayEdit'];
  onSaveTransportDetails: TravelTimelineNodeProps['onSaveTransportDetails'];
  onBeginItemEdit: TravelTimelineNodeProps['onBeginItemEdit'];
  onAddPhotos: TravelTimelineNodeProps['onAddPhotos'];
  onRemovePhoto: TravelTimelineNodeProps['onRemovePhoto'];
  onRemove: TravelTimelineNodeProps['onRemove'];
  setEditingTransport: (value: boolean) => void;
  setNotesOpen: (value: boolean) => void;
  openBooking: () => void;
};
